"""init_db

Revision ID: 5cf8f5a995cc
Revises: 
Create Date: 2025-11-26 13:49:25.249628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cf8f5a995cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='手机号 (核心登录凭证, E.164格式)'),
    sa.Column('username', sa.String(length=50), nullable=True, comment='用户名 (对外展示/备选登录)'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='用户邮箱'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='密码哈希值'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment='用户全名/昵称'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否超级管理员'),
    sa.Column('id', sa.UUID(), nullable=False, comment='主键 (UUID v7)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间 (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间 (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否软删除'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间 (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('phone_number', name=op.f('uq_users_phone_number')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
